version: "3"

services:
  app:
    image: fadyyousef/simple-cicd-app:latest
    container_name: app
    ports:
      - "8080:8080"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 springboot-app
