name: Build and Deploy spring boot app

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v5

      - name: setup jdk java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the application
        run: mvn -B package --file pom.xml
      